### ISSUE TITLE
[Request] Import rcc_msk_2021 into MSK Portal

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#582]
## Request
Need to import `rcc_msk_2021` into MSK Portal but running into errors

## Error
```
java.lang.RuntimeException: org.apache.commons.lang.exception.NestableRuntimeException: Invalid arguments for run() method in: org.mskcc.cbio.portal.scripts.ImportCopyNumberSegmentData
	at org.mskcc.cbio.importer.util.MSKTransactionalScriptRunner.run(MSKTransactionalScriptRunner.java:80)
	at org.mskcc.cbio.importer.internal.ImporterImpl.loadCancerStudyStagingFiles(ImporterImpl.java:618)
```

**Comment by averyniceday** [comment]
`int numProbes = new BigDecimal((strs[4])).intValue();` 

This line is failing -- looks like our code is written to expect a numerical value. 

Double checked the DB and it looks like the num.mark / probe field is not allowed to be null. 

Temporarily recommended setting it to 0 in the MAF as a NA/empty placeholder. Separate conversation to be had about what the field is and whether NA is allowed and whether 0 is an okay substitute.
