### ISSUE TITLE
GDAC Functional on eks-pipelines

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#654]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Updates (including import scripts) run on EKS pipelines - and database is up to date
## Technical Description (How are we going to achieve the above)
Dump DB, test runs of import scripts

**Comment by sheridancbio** [comment]
yesterday, the cgds_gdac database was dumped and loaded / updated on the eks pipeline node. It is now considered 'live'. The .war deployments for schultz-tomcat and msk-tomcat on dashi/dashi2 servers were redeployed with a new tomcat data resource reference which points to the mysql server on the eks pipelines node.
also, a cmo importer was deployed to the eks pipelines node and the import-cmo-data-msk.sh script was run [via the crontab] to import 2 studies into the msk portal. The msk war files on dashi/dashi2 were manually restarted to make the studies visible.

**Comment by sheridancbio** [comment]
today the focus will be on the other fetch-and-import-dmp-data-wrapper.sh steps and preparing for a full dmp fetch/load cycle tonight, and also on the restart / recache needs of the systems.

one other need is to propagate the cbioportal hash we are currently building with (f846d3c6cefb14d1d8ea4ab39889c45d557e33d1) through genome-nexus-annotation-pipeline and pipeline code bases so that importers can be properly built using the build script on the eks pipelines node

**Comment by averyniceday** [comment]
Immediate Work Left:
- [x] Darwin Sock Fix
- [ ] Switchover with Franklin
- [ ] Google domain updates to redirect
- [ ] Update Crontab

Upcoming Work:
- [ ] Start new cluster with new VPC

**Comment by sheridancbio** [comment]
Several days last sprint were spent debugging failures in the dmp import job. The upstream server (lynx) was refusing to deliver any of the mskimpact cohort samples because it has received a non-ascii character of some sort which was causing an internal exception to be thrown and our importer execution was receiving a 500 Internal Server Error response from lynx. This problem has persisted for a long time (weeks). Eventually, the dmp team was able to suppress/skip over the problematic samples so that we could others. However, a large backlog of un-consumed samples had built up and needed to be processed in smaller batches.

**Comment by sheridancbio** [comment]
Working through the backlog was hampered by a misunderstanding about the running of the cvr-fetcher to consume samples. The first misconception was that the .json formatted download from the lynx server could be fed in (with the -c command line option) as the set of samples which were to be consumed. This is not true ... no samples will be consumed this way. What is required as an input set for consumption is the transformed "cvr_data.json" file which includes much of the information from the direct download, but with some additions and reformatting.

The second misunderstanding involved the filename provided with the "-c" command line option. If the user provides the literal string "cvr_data.json" then then cvr-fetcher will create a session with the endpoint from which we get somatic sample information. Any other provided filename results in a session being created through the endpoint from which we retrieve germline sample information. Because we were trying to consume somatic sample information with a modified filename, the authentication was failing because the session id which was created was for the wrong endpoint. The rule is : to consume somatic samples, the input file must exactly match "cvr_data.json" and the user must not use the -g (germline mode) command line flag. To consume germline samples, the filename is irrelevant. I did not test this, but I assume that you also must use the "-g" germline mode flag.

**Comment by sheridancbio** [comment]
There were about 1500 samples in the backlog. They were split into 7 batches of ~210 samples and processed with the cvr fetch step without running the rest of the fetch and import logic. It was stated that the linkage of archer fusions samples to processed batches would succeed in one pass after all 7 batches had been fetch separately. Processing the 7 batches took about a full day.

**Comment by sheridancbio** [comment]
After the commits of the cvr fetches for the 7 batches had been pushed into the dmp-2021 data repository, the full fetch-dmp-impact-data wrapper script was run. It mysteriously stalled during the consumption step of the mskimpact germline samples. The stall persisted for about 7 hours and was manually killed. After that the rest of the import process completed. There were errors reported in the log files, but many of these errors are routinely reported and were present on the pipelines server execution logs too.

The errors were captured (see below) and reviewed. One correction which was made in response to the errors was to edit /home/cbioportal_importer/.hgrc to enable the "purge" plugin for mercurial.

Another correction was to add the missing python module jinja2 for the script /data/portal-cron/git-repos/cbioportal/core/src/main/scripts/importer/validateData.py

**Comment by sheridancbio** [comment]
Other errors were discussed and deprioritized - it might  be good to add cards to the product backlog if we wish to address any of these:
Traceback (most recent call last):
  File "/data/portal-cron/scripts/cvr_consent_status_checker.py", line 187, in <module>
    main()
  File "/data/portal-cron/scripts/cvr_consent_status_checker.py", line 183, in main
    expected_consent_status_values = fetch_expected_consent_status_values()
  File "/data/portal-cron/scripts/cvr_consent_status_checker.py", line 42, in fetch_expected_consent_status_values
    response = urllib.urlopen(url)
  File "/usr/lib64/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib64/python2.7/urllib.py", line 215, in open
    return getattr(self, name)(url)
  File "/usr/lib64/python2.7/urllib.py", line 352, in open_http
    h.endheaders(data)
  File "/usr/lib64/python2.7/httplib.py", line 1078, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 894, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 856, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 833, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
IOError: [Errno socket error] [Errno 110] Connection timed out
-------------------------------
Consuming mskimpact samples from cvr
-- Rob: this step failed but the failure was not detected
-------------------------------
Adding clinical attribute meta data headers...
Error code returned from CDD, aborting...
Error while attempting to add clinical attribute meta data headers to /data/portal-cron/cbio-portal-data/crdb_pdx/mixed_pdx_msk/lung_msk_pdx/data_clinical*
-------------------------------
commit ddp timeline data for MSKSPECTRUM
[master 5327062] Latest MSKSPECTRUM DDP timeline data
 Committer: importer system account <cbioportal_importer@ip-10-1-21-42.cbioportal.aws.mskcc.org>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 3 files changed, 1944 insertions(+)
 create mode 100644 msk_spectrum/data_timeline_ddp_chemotherapy.txt
 create mode 100644 msk_spectrum/data_timeline_ddp_radiation.txt
 create mode 100644 msk_spectrum/data_timeline_ddp_surgery.txt
ERROR: Repository not found.
fatal: Could not read from remote repository.
-------------------------------
redcap pipeline issues
-------------------------------
2021-09-29 23:40:06 [main] INFO  org.mskcc.cmo.ks.redcap.pipeline.ClinicalDataReader - Clinical attribute PARTC_CONSENTED_12_245 for record with PATIENT_ID:P-0016649 was previously seen with value 'NO' but another conflicting value has been encountered : 'YES' - ignoring this subsequent value.
2021-09-30 00:50:22 [main] INFO  org.mskcc.cmo.ks.redcap.pipeline.ClinicalDataReader - Clinical attribute PARTC_CONSENTED_12_245 for record with PATIENT_ID:P-0068701 was previously seen with value 'YES' but another conflicting value has been encountered : 'NO' - ignoring this subsequent value.
2021-09-30 00:50:34 [main] INFO  org.mskcc.cmo.ks.redcap.pipeline.ClinicalDataReader - Clinical attribute OS_STATUS for record with PATIENT_ID:P-0019756 was previously seen with value 'LIVING' but another conflicting value has been encountered : 'DECEASED' - ignoring this subsequent value.
-------------------------------
cvr fetch pipeline issues
-------------------------------
2021-09-30 10:55:46 [main] ERROR org.cbioportal.cmo.pipelines.cvr.consume.ConsumeSampleWriter - Error consuming sample P-0043748-T01-XS1(org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.cbioportal.cmo.pipelines.cvr.model.CVRConsumeSample] and content type [text/html;charset=utf-8])
2021-09-30 11:03:14 [main] ERROR org.cbioportal.cmo.pipelines.cvr.consume.ConsumeSampleWriter - Error consuming sample P-0018768-T01-AS1(org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.cbioportal.cmo.pipelines.cvr.model.CVRConsumeSample] and content type [text/html;charset=utf-8])
2021-09-30 15:00:23 [main] ERROR org.cbioportal.cmo.pipelines.cvr.consume.ConsumeSampleWriter - Error consuming sample P-0069110-N01-IM7(org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.cbioportal.cmo.pipelines.cvr.model.CVRConsumeSample] and content type [text/html;charset=utf-8])
-------------------------------
There are many thousands (>240000) of reported annotation errors: (Nonsigned out variant count for mskimpact : 1725971 for example, germline is 504481
-------------------------------
-------------------------------
2021-09-30 23:00:40 [main] WARN  org.cbioportal.cmo.pipelines.cvr.requeue.CvrRequeueListener - 37 samples from the dmp master list failed to requeue
-------------------------------
2021-09-30 23:00:40 [main] WARN  org.cbioportal.cmo.pipelines.cvr.requeue.CvrRequeueListener - 542 portal samples are not in the dmp master list
2021-09-30 23:00:40 [main] WARN  org.cbioportal.cmo.pipelines.cvr.requeue.CvrRequeueListener - Portal sample 'P-0056068-T01-AS1' is not in the dmp master list
...
-------------------------------
2021-09-30 23:06:35 [main] ERROR org.cbioportal.cmo.pipelines.cvr.cna.CVRCnaDataReader - Cannot find gene panel file: impact468_gene_panel.txt
-------------------------------
2021-10-01 01:10:10 [main] ERROR org.cbioportal.cmo.pipelines.cvr.consume.ConsumeSampleWriter - Error consuming sample P-0040788-N01-IM6(org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.cbioportal.cmo.pipelines.cvr.model.CVRConsumeSample] and content type [text/html;charset=utf-8])
-------------------------------
2021-10-01 01:20:17 [main] ERROR org.cbioportal.cmo.pipelines.cvr.consume.ConsumeSampleWriter - Error consuming sample P-0037520-T01-AS1(org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [class org.cbioportal.cmo.pipelines.cvr.model.CVRConsumeSample] and content type [text/html;charset=utf-8])


There are also steps we could take to cut down on the noise going into the importer component logs.
SLF4J: Found binding in [jar:file:/data/portal-cron/lib/darwin_fetcher.jar!/BOOT-INF/lib/redcap_source-0.1.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/data/portal-cron/lib/darwin_fetcher.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
-------------------------------
beginning push of dmp data updates to git repository Thu Sep 30 01:07:09 EDT 2021...
Locking support detected on remote "origin". Consider enabling it with:
  $ git config lfs.https://github.mskcc.org/knowledgesystems/dmp-2021.git/info/lfs.locksverify true
Uploading LFS objects: 100% (137/137), 6.1 GB | 31 MB/s, done.
-------------------------------

**Comment by averyniceday** [comment]
Work with Aaron to resolve this issue and contact Franklin 

`Cannot construct instance of org.cbioportal.model.GeneFilterQuery (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('BRAF')`

Done condition is the msk portal is in EKS
