### ISSUE TITLE
investigate missing import notification email 2021_10_27

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#726]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Find out why no notification mail was sent for the msk-automation-portal import.

**Comment by sheridancbio** [comment]
Investigated the msk-cmo-importer.log and saw that towards the end of the import there was this exception in the logs:
2021-10-27 04:36:52 [main] ERROR org.mskcc.cbio.importer.util.MSKTransactionalScripts - Failed import of org.mskcc.cbio.portal.scripts.ImportCopyNumberSegmentData with args: --data /data/portal-cron/cbio-portal-data/crdb_pdx/mixed_aac/mixed_aac_data_cna_hg19.seg --study mixed_aac -a -r
2021-10-27 04:36:52 [main] INFO  org.mskcc.cbio.importer.Admin - java.lang.RuntimeException: org.apache.commons.lang.exception.NestableRuntimeException: Invalid arguments for run() method in: org.mskcc.cbio.portal.scripts.ImportCopyNumberSegmentData
        at org.mskcc.cbio.importer.internal.ImporterImpl.updateCancerStudy(ImporterImpl.java:187)
        at org.mskcc.cbio.importer.Admin.updateStudyData(Admin.java:521)
        at org.mskcc.cbio.importer.Admin.run(Admin.java:341)
        at org.mskcc.cbio.importer.Admin.main(Admin.java:850)
Caused by: org.apache.commons.lang.exception.NestableRuntimeException: Invalid arguments for run() method in: org.mskcc.cbio.portal.scripts.ImportCopyNumberSegmentData
        at

So some kind of problem with seg data was flagged. But the notification file was still present on the system and it showed that all studies imported were missing the case_lists subdirectory:
mixed_pdx_abou_alfa
java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: /data/portal-cron/cbio-portal-data/crdb_pdx/mixed_pdx_abou_alfa/case_lists (No such file or directory)

There may be multiple errors here. The curators were notified
