### ISSUE TITLE
investigate and correct failure to merge archer fusions

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#740]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
The archer fusion merger step is succeeding again

## Technical Description (How are we going to achieve the above)
There are errors in the logs for at least the last two days (today: 2021_11_02) just before the step "beginning redcap import for all cohorts" which show failure to merge archer fusions using the script archer_fusions_merger.py into mskimpact and mskimpact_heme. We will identify what is failing and correct or work around it.

**Comment by sheridancbio** [comment]
latest stacktrace:
Traceback (most recent call last):
  File "/data/portal-cron/scripts/archer_fusions_merger.py", line 257, in <module>
    main()
  File "/data/portal-cron/scripts/archer_fusions_merger.py", line 254, in main
    merge_fusions(archer_fusions_filename, fusions_filename, linked_cases_filename, clinical_filename, mapped_archer_samples_filename, study_id, gmail_username, gmail_password)
  File "/data/portal-cron/scripts/archer_fusions_merger.py", line 209, in merge_fusions
    send_samples_missing_clinical_data_report(study_id, clinical_filename, gmail_username, gmail_password)
  File "/data/portal-cron/scripts/archer_fusions_merger.py", line 175, in send_samples_missing_clinical_data_report
    s = smtplib.SMTP_SSL(SMTP_SERVER, 465)
  File "/usr/lib64/python2.7/smtplib.py", line 802, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 807, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable

**Comment by sheridancbio** [comment]
The error raised is at the point where an email send is occurring:
173         print >> OUTPUT_FILE, "Sending email..."
174         # send email
175         s = smtplib.SMTP_SSL(SMTP_SERVER, 465)
176         s.login(gmail_username, gmail_password)
177         s.sendmail(MESSAGE_SENDER, MESSAGE_RECIPIENTS, msg.as_string())
178         s.quit()

**Comment by sheridancbio** [comment]
Here SMTP_SERVER = "smtp.google.com"

We had a specific workaround for port 25 traffic to allow it to go to cbio.mskcc.org, but this server is outside of our network. This may be the issue. We seem to be using port 465 however. Possibly this is blocked too

**Comment by sheridancbio** [comment]
This functionality seemed to work correctly today (Nov 2/3 import). The two prominent possibilities. The failures have been occurring consistently over the past 4 weeks, and they were occurring between ~10pm and midnight. The success was at 8:52pm last night, which is only a little earlier than the most early time which failed (9:12pm on Oct 19). So it is probably not time dependent. Just to check on this possibility I am running a 24 hour script which sends a pair of email messages every 10 minutes fo the next 24 hours. We will see if failures occur and what time of day they do [if they do].
The other possibility is that some correction to the networking or mail server was performed.  @averyniceday did some kind of fix to point the local mail server at the gmail server rather than the cbio.mskcc.org server. Possibly that change smoothed the way for the notifications from the script to go to the gmail server. Or maybe somebody cleaned out a full gmail account mailbox or something. In any case, if the imports continue smoothly for the next several days we can say that the problem which was happening consistent between Oct 3 and Nov 3 is no longer present.
