### ISSUE TITLE
Debug, detect, and report corrupted type_of_cancer table

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#826]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Either the cbioportal importer reports directly in the logs when the type_of_cancer table is invalid, or a separate utility does.

## Technical Description (How are we going to achieve the above)
Independent option :
write a script to validate the table content which runs separately
Embedded/integrated option:
Validate the type_of_cancer contents before or during the construction of the parent map in CancerTypeServiceImpl. If there are nodes for which the parent is not found, report the problem in the logs (naming the node and the missing parent). It would also be good to suggest a repair strategy. (There is a foreign key from cancer_study to type_of_cancer, so repair my be tricky ... I repaired manually by adding placeholders for missing parental nodes, including the "tissue" root node .. then we re-imported the full type_of_cancer table using the built-in importer functionality ... perhaps a similar automated approach which adds tissue and then makes tissue the parent of any existing node which is missing a parent)

**Comment by sheridancbio** [comment]
When the type_of_cancer table gets corrupted, the importer will fail to initialize properly on startup with this exception:
Exception in thread "main" org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mutationSpectrumServiceImpl': Unsatisfied dependency expressed through field 'mutationService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mutationServiceImpl': Unsatisfied dependency expressed through field 'molecularProfileService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'molecularProfileServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
...
        at org.mskcc.cbio.importer.Admin.main(Admin.java:847)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mutationServiceImpl': Unsatisfied dependency expressed through field 'molecularProfileService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'molecularProfileServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'molecularProfileServiceImpl': Unsatisfied dependency expressed through field 'studyService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
...
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'studyServiceImpl': Unsatisfied dependency expressed through field 'cancerTypeService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cancerTypeServiceImpl': Invocation of init method failed; nested exception is java.util.NoSuchElementException: No value present
...
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at org.cbioportal.service.impl.CancerTypeServiceImpl.getParent(CancerTypeServiceImpl.java:76)

This will occur when there are nodes in the table which refer to a non-existent parent. However the exception above hides the problem deeply.
